{% set version = "0.6.dev" %}

package:
  name: tvm-libs
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  string: cuda{{ cuda_version }}_{{ PKG_BUILDNUM }}  # [cuda]

requirements:
  build:
    # The OS X build will require some manual setup or it will break
    # See https://docs.conda.io/projects/conda-build/en/latest/source/resources/compiler-tools.html#macos-sdk
    - {{ compiler('cxx') }}
  host:
    - cmake
    - llvmdev ==6.0.0
    - zlib  # [linux]
  run:
    - {{ pin_compatible('cudatoolkit', lower_bound=cuda_version, max_pin='x.x') }}  # [cuda]

about:
  home: https://github.com/dmlc/tvm
  license: Apache2
  summary: a low level domain specific language for compiling tensor computation pipelines